### ISSUE TITLE
Settings Load Crash

### ISSUE THREAD

**Issue by Pheenoh** [zsrtp/tpgz#20]
Loading the GZ settings at boot causes a crash when the memory card is corrupt.

Might be worth looking into this function: `mDoMemCdRWm_CheckCardStat` . It sets card state to fatal error if it returns false

**Comment by kipcode66** [comment]
It's going to be hard to test since I'm not sure if there is a way to purposefully corrupt a save file, either on dolphin or on a console.

**Comment by Pheenoh** [comment]
I believe this was fixed in #46 with the adding of the missing memory card status checks. Will reopen if not.
