### ISSUE TITLE
Wii Support

### ISSUE THREAD

**Issue by Pheenoh** [zsrtp/tpgz#26]
Add support for the Wii versions of the game

**Comment by kipcode66** [comment]
I only had the NTSCU 1.0 and PAL versions of the game, so I am not able to test and find the right addresses for the NTSCU 1.2, NTSCJ, and Korean versions of the game. Unless someone else with those versions steps in, we'll probably need to wait I acquire them to finish the support for all Wii versions.

**Comment by TakaRikka** [comment]
I can get 1.2 and J addresses, not sure if they'll need any alignment changes though

**Comment by kipcode66** [comment]
1.2 support was added in the cmake branch. It will probably be merged soon.

**Comment by kipcode66** [comment]
Every Wii versions (except korean) is working on the branch 0.5fixes. The pr #71 will close this issue.
